### ISSUE TITLE
Not able to import local image

### ISSUE THREAD

**Issue by varunyn** [rtivital/react-pages-boilerplate#4]
import logo from '../../../assets/architecture/01.png';

 <img src={logo}/>

No image is shown when importing like this way, I tried to find the solution couldn't get any.

**Comment by rtivital** [comment]
You should place image in src folder and import it from there

**Comment by varunyn** [comment]
It's inside the src folder but still unable to load, I also have the same issue with local json file

**Comment by rtivital** [comment]
please provide project code or example
